### ISSUE TITLE
`Memcached#decrement` results in a client error when decrementing a value to unsigned integer

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cache-storage-adapter-memcached#17]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | latest
| ext-memcached | 3.1.5
| Memcached | 1.6.10

#### Summary

When calling `Memcached#decrement` twice with the same key, it returns `false` and the status code `9` which translates to the `RES_CLIENT_ERROR` constant.

When `Memcached#getLastErrorMessage` is called, we get more details on this:
```
(0x7ff922d5da40) cannot increment or decrement non-numeric value
```

#### Current behavior

- First call to `Memcached#decrement` creates and decrements the key.
- Second call returns false while not touching the key at all (it remains on the initial value)

#### How to reproduce

```php
$memcached = new Memcached(); // set options to point to the appropriate memcached server instance
$memcached->decrementItem('foo', 1);
$memcached->decrementItem('foo', 1);

assert($memcached->getItem('foo') === -2);
```

#### Expected behavior

Assertion works.

**Comment by ferdousulhaque** [comment]
@boesing Memcached only supports unsigned integer for increment or decrement. So I think the assertion will be incorrect in this case.

[Reference Link](https://www.php.net/manual/en/memcached.decrement.php#:~:text=%24m-%3Edecrement(%27counter%27%2C%C2%A010)%3B)

**Comment by boesing** [comment]
I had a look on this. 
So memcached is not able to actually decrement to a value lower than `0`.

----

From what I can see, the initial `decrementItem` call uses `memcached#decrement` to decrement a non-existing key. 
Since we have a handling for non-existing keys, we use `memcached#add` with an initial value (in the example above that would be `-1`).
It seems that creating a new cache item with a negative integer is not a real problem for memcached and therefore does not return an error. At least none is thrown which tells me that it might have worked.

So only the second call triggers an error. I wonder why the first one is already "okay" tho.
Maybe refactoring the "item not found" error in `Memcached#decrementItem` to initially set `0` rather than `-$value` would be a better idea since using a negative integer would still end in a `0` value.

### Refs

https://github.com/laminas/laminas-cache-storage-adapter-memcached/blob/e67cfcb4e9ccca19890e6737262b91c1904f68da/src/Memcached.php#L542

https://github.com/laminas/laminas-cache-storage-adapter-memcached/blob/e67cfcb4e9ccca19890e6737262b91c1904f68da/src/Memcached.php#L546

https://github.com/laminas/laminas-cache-storage-adapter-memcached/blob/e67cfcb4e9ccca19890e6737262b91c1904f68da/src/Memcached.php#L549

**Comment by boesing** [comment]
Closing this as won't fix for now.
Memcached is not able to decrement to negative integers and thus a proper fix is not possible.

There is already an [RFC in the cache component](https://github.com/laminas/laminas-cache/issues/117) where I suggest to remove this feature at all from `laminas-cache`.
I will most likely remove that feature in v4.0.0 and thus we have to release a new major in the adapters anyways which then closes this problem.

I'd rather move the whole logic to application-side, either by using the cache backend directly in case one wants to use the server-side logic (i.e. memcached, redis, etc. - due to its race-condition-safe handling) or by writing own logic.

IMHO it should not be provided by laminas-cache in a generic way, esp. due to the fact that not all backends are implementing dedicated logic but generic logic in the `AbstractStorageAdapter`:

https://github.com/laminas/laminas-cache/blob/52182084683faaea3a52bc7f9184a5d8528782ce/src/Storage/Adapter/AbstractAdapter.php#L1249-L1263
