### ISSUE TITLE
Add PHP 8.1 support

### ISSUE THREAD

**Issue by Koen1999** [laminas/laminas-cache-storage-adapter-memcached#20]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Add support for the newly released PHP 8.1

**Comment by froschdesign** [comment]
@Koen1999 
Please check [version 2.0.0](https://github.com/laminas/laminas-cache-storage-adapter-memcached/releases/tag/2.0.0) of this adapter.

**Comment by boesing** [comment]
Please migrate to `laminas-cache` v3 along with v2.0 of this adapter.

**Comment by Koen1999** [comment]
Woops, that's my bad. Thanks for the quick response!
I'll look into upgrading our dependencies to support laminas-cache v3 as well.
